In [7]:
import numpy as np

arr = np.array([1,3,5,-7,14])
arr = arr.astype('int64')
print(arr.dtype)
sum = arr.sum()
ones = np.ones(5)
min = np.min(arr)
max = np.max(arr)
print(arr, sum, ones)
print(min, max)

int64
[ 1  3  5 -7 14] 16 [1. 1. 1. 1. 1.]
-7 14


In [8]:
zeroes = np.zeros(5)
empty = np.empty([5,5])
random = np.random.random(5)
linspace = np.linspace(5, stop=2)
print(zeroes, "\n", empty, "\n",random, "\n",linspace)

[0. 0. 0. 0. 0.] 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 
 [0.20862319 0.10547534 0.65838439 0.44159704 0.12134991] 
 [5.         4.93877551 4.87755102 4.81632653 4.75510204 4.69387755
 4.63265306 4.57142857 4.51020408 4.44897959 4.3877551  4.32653061
 4.26530612 4.20408163 4.14285714 4.08163265 4.02040816 3.95918367
 3.89795918 3.83673469 3.7755102  3.71428571 3.65306122 3.59183673
 3.53061224 3.46938776 3.40816327 3.34693878 3.28571429 3.2244898
 3.16326531 3.10204082 3.04081633 2.97959184 2.91836735 2.85714286
 2.79591837 2.73469388 2.67346939 2.6122449  2.55102041 2.48979592
 2.42857143 2.36734694 2.30612245 2.24489796 2.18367347 2.12244898
 2.06122449 2.        ]


In [9]:
stacked = np.stack([ones, zeroes], axis=0)
print(stacked)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


In [10]:
concat = np.concatenate([random, linspace], axis=0)
print(concat)

[0.20862319 0.10547534 0.65838439 0.44159704 0.12134991 5.
 4.93877551 4.87755102 4.81632653 4.75510204 4.69387755 4.63265306
 4.57142857 4.51020408 4.44897959 4.3877551  4.32653061 4.26530612
 4.20408163 4.14285714 4.08163265 4.02040816 3.95918367 3.89795918
 3.83673469 3.7755102  3.71428571 3.65306122 3.59183673 3.53061224
 3.46938776 3.40816327 3.34693878 3.28571429 3.2244898  3.16326531
 3.10204082 3.04081633 2.97959184 2.91836735 2.85714286 2.79591837
 2.73469388 2.67346939 2.6122449  2.55102041 2.48979592 2.42857143
 2.36734694 2.30612245 2.24489796 2.18367347 2.12244898 2.06122449
 2.        ]


In [11]:
argmin = np.argmin(arr)
argmax = np.argmax(arr)
print(argmin, argmax)

3 4
