In [4]:
import numpy as np

arr = np.array([1,3,5,-7,14])
arr = arr.astype('int64')
print(arr.dtype)
sum = arr.sum()
ones = np.ones(5)
min = np.min(arr)
max = np.max(arr)
print(arr, sum, ones)
print(min, max)

int64
[ 1  3  5 -7 14] 16 [1. 1. 1. 1. 1.]
-7 14


In [5]:
zeroes = np.zeros(5)
empty = np.empty([5,5])
random = np.random.random(5)
linspace = np.linspace(num=5, start=0, stop=2)
print(zeroes, "\n", empty, "\n",random, "\n",linspace)

[0. 0. 0. 0. 0.] 
 [[4.67896683e-310 0.00000000e+000 6.90906383e-310 6.90906401e-310
  6.90906404e-310]
 [6.90906402e-310 6.90906402e-310 6.90906383e-310 6.90906383e-310
  6.90906400e-310]
 [6.90906383e-310 6.90906383e-310 6.90906400e-310 6.90906398e-310
  6.90906399e-310]
 [6.90906402e-310 6.90906401e-310 6.90906402e-310 6.90906404e-310
  6.90906403e-310]
 [6.90906400e-310 6.90906400e-310 6.90906386e-310 6.90906393e-310
  1.02765654e-321]] 
 [0.29239842 0.43718975 0.16436337 0.36844196 0.89436125] 
 [0.  0.5 1.  1.5 2. ]


In [6]:
stacked = np.stack([ones, zeroes], axis=0)
print(stacked)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


In [7]:
concat = np.concatenate([random, linspace], axis=0)
print(concat)

[0.29239842 0.43718975 0.16436337 0.36844196 0.89436125 0.
 0.5        1.         1.5        2.        ]


In [8]:
argmin = np.argmin(arr)
argmax = np.argmax(arr)
print(argmin, argmax)

3 4


In [20]:
rands = np.random.randint(10, size=4)
print(rands)
reshape = rands.reshape([2,2])
print(reshape)
transpose = reshape.transpose()
print(transpose)

[7 1 4 4]
[[7 1]
 [4 4]]
[[7 4]
 [1 4]]
